### ISSUE TITLE
Error When Building mavproxy.py

### ISSUE THREAD

**Issue by OpenGelo** [tridge/MAVProxy#107]
I want to compile mavproxy source code from github, I downloaded the zip and extract it in the Python27 directory.
i've downloaded all packages requaired to build mavpoxy on Windows
I also have followed the instructions in the mavproxy documentation and dev.ardupilot.com
But I got the same problem.
The problem is there is no module named MAVProxy.modules.lib
So, how to solve this?

P.S. I also tried in linux but got the other problem, I'm a newbie in python.

**Comment by gmorph** [comment]
This isn't an issue in the application so should not be raised as such.  Your best bet for this sort of question is to head over to gitter and ask this sort of thing there.  To answer your question:
You should extract the zip in your home directory - not the Python27 directory.
Adding the MAVProxy directory may also help.
This is the command I run to build and subsequently install mavproxy in my local account
    python setup.py build install --user
Thanks, Grant.
