### ISSUE TITLE
typing "guided 10 10 10" to mavproxy causes exception

### ISSUE THREAD

**Issue by sethjhs** [tridge/MAVProxy#139]
Probably best to just try this command and see but I get the exception:

"ERROR in command: local variable 'latlon' referenced before assignment"

The error is pretty obvious when you look at the code but in MAVProxy/MAVProxy/modules/mavproxy_mode.py in cmd_guided lines 49-52, latlon should be defined.

**Comment by gmorph** [comment]
Thanks.  Are you going to submit a pull request?  If not I will.

**Comment by sethjhs** [comment]
Yep, im not planning on making a pull request

**Comment by gmorph** [comment]
Fixed by this pull request.
https://github.com/tridge/MAVProxy/pull/140
Thanks.
