### ISSUE TITLE
Hardcoded paths called 

### ISSUE THREAD

**Issue by lvale** [tridge/MAVProxy#147]
Some commands and functions refer to hardcoded paths that are not present on a user machine (latest Win Version). As an example:

Loaded module console
MAV> ERROR in command: 'NoneType' object has no attribute 'waypoint_clear_all_se
nd'
Traceback (most recent call last):
  File "<string>", line 462, in process_stdin
  File "C:\PROGRA~2\MAVProxy\eggs\mavproxy-1.4.11-py2.7.egg\MAVProxy\modules\mav
proxy_wp.py", line 525, in cmd_wp
    self.master.waypoint_clear_all_send()
AttributeError: 'NoneType' object has no attribute 'waypoint_clear_all_send'
ERROR in command: 'NoneType' object has no attribute 'param_set_send'
Traceback (most recent call last):
  File "<string>", line 462, in process_stdin
  File "C:\PROGRA~2\MAVProxy\eggs\mavproxy-1.4.11-py2.7.egg\MAVProxy\modules\mav
proxy_fence.py", line 192, in cmd_fence
    self.param_set('FENCE_TOTAL', 0, 3)
  File "C:\PROGRA~2\MAVProxy\eggs\mavproxy-1.4.11-py2.7.egg\MAVProxy\modules\lib
\mp_module.py", line 102, in param_set
    self.mpstate.functions.param_set(name, value, retries)
  File "<string>", line 211, in param_set
  File "C:\Users\tridge\Documents\GitHub\MAVProxy\MAVProxy\build\mavproxy\out00-
PYZ.pyz\pymavlink.mavparm", line 22, in mavset
AttributeError: 'NoneType' object has no attribute 'param_set_send'

**Comment by stephendade** [comment]
There's an updated version of MAVProxy at http://firmware.diydrones.com/Tools/MAVProxy/ that should help you.

**Comment by lvale** [comment]
Downloaded the "latest" (I assume the latest is 2015-05-13) and similar issues 
![screen shot 2015-05-20 at 11 42 13](https://cloud.githubusercontent.com/assets/3130363/7724032/b0d5f2b6-fee5-11e4-986b-0b4439514473.png)

**Comment by stephendade** [comment]
I can't seem to be able to replicate the issue. Which flight controller (and version) and you connecting to?
Are you running MAXProxy with any commandline options?

**Comment by lvale** [comment]
No FC attached. And also no cmdline options on the screenshot.

**Comment by stephendade** [comment]
Any chance you could scroll to the top of your console so I could see the entire output? It should start with "Logging to mav.tlog"

**Comment by lvale** [comment]
The console when opened, without any commands issued, yet. Still the eggs dir :)

![screen shot 2015-05-20 at 22 18 28](https://cloud.githubusercontent.com/assets/3130363/7736798/4b9a0ec4-ff3e-11e4-8500-dda55562d3d2.png)

**Comment by lvale** [comment]
btw:

This is quite easy to duplicate. The screenshots are from a freshly installed Windows7-64. So a similar VM with a freshly installed (and Windows updated) replicates this behavior easily...

**Comment by stephendade** [comment]
The "Using deprecated class PySimpleApp" message is a known warning. It doesn't affect the functionality of the program.
As for the "EOFError", that is normal when exiting MAVProxy.
How did you get the "Nonetype object has no attribute 'param_set_send' error from previously? I'm unable to replicate that particular message.

**Comment by lvale** [comment]
If I remember correctly that came up because I chose Clear Mission without FC attached.

**Comment by stephendade** [comment]
Ahh yes, I see now.

The issue is that some MAVProxy modules don't check to see if there's a valid connection before executing a command.

The hardcoded directories in the error messages are an artifact of the compilation process, but do not affect the running of the program.

**Comment by lvale** [comment]
ok. thanks
