### ISSUE TITLE
Modules on Raspberry Pi

### ISSUE THREAD

**Issue by unphased** [tridge/MAVProxy#50]
I have tried installing MAVProxy with `pip` and with the `python setup.py build && python setup.py install` and I only get this list: 

```
STABILIZE> module list
STABILIZE> log: log transfer
wp: waypoint handling
rally: rally point control
fence: geo-fence management
param: parameter handling
relay: relay handling
tuneopt: tuneopt command handling
arm: arm/disarm handling
mode: mode handling
calibration: calibration handling
rc: rc command handling
auxopt: auxopt command handling

STABILIZE> module load map
STABILIZE> Failed to load module: No module named map
```

It's like this whether i call the one in the build directory, the one in the source directory, or the one in the install directory `/usr/local/bin`. 

Is this expected? I was sort of hoping I can get the modules like map and console and whatever else to work when x is running on the raspberry pi.  Also, it's not very clear at all how modules work, how they're loaded, and how I can make a new module.

**Comment by gmorph** [comment]
Closing as original issue is resolved.
Thanks, Grant.

**Comment by deinelakaien** [comment]
I found better solution that doesn't require manual checking and re-installation of python modules. Just install these modules:
sudo apt-get install python-matplotlib python-serial python-wxgtk2.8 python-lxml
sudo apt-get install python-scipy python-opencv ccache gawk git python-pip python-pexpect

Found it here http://dev.ardupilot.com/wiki/simulation-2/sitl-simulator-software-in-the-loop/setting-up-sitl-on-linux/

Hope it helps

**Comment by hsuhonghai** [comment]
it's true, it works  ([thelastpolaris]
